version: '3.4'

x-default: &default
  image: web
  depends_on:
    - db
    - redis
  env_file:
    - .env

services:
  redis:
    image: redis:5.0.3-alpine
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    <<: *default
    command: sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
  worker:
    <<: *default
    command: rake resque:work
    environment:
      - QUEUE=*
  scheduler:
    <<: *default
    command: rake resque:scheduler
